import React, { useState } from 'react'

const Contact = () => {
   let count = 0
    for(let i=0;i<1000000000;i++){
        count +=1;
    }
  return (
    <div>
        <h4>Count is -- {count}</h4>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
      <h3>Contact Component</h3>
    </div>
  )
}

export default Contact
